name: Build and push typst tooling container

on:
  push:
    branches: ["master"]
    paths:
      - ".github/workflows/typst-container.yaml"
      - "Dockerfile"

  workflow_dispatch:

permissions:
  contents: read
  packages: write

concurrency:
  group: "container"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: log in to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/typst-cli:latest
